# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

convert_unitsC <- function(x, from, to) {
    .Call(`_fgeo_biomass_convert_unitsC`, x, from, to)
}

